### ISSUE TITLE
loading any rust file freezes the atom v0.196 

### ISSUE THREAD

**Issue by AtlasInsight** [zargony/atom-language-rust#29] opened 2015-05-05 17:52 UTC

**Comment by redefiance** [comment] 2015-05-05 20:03
The problem seems to lie with this line
```cson
'scopeName': 'source.rust'
```
If I change it to
```cson
'scopeName': 'source.corrode'
```
everything seems to be working fine and I still get syntax highlighting

**Comment by d-rezzer** [comment] 2015-05-05 22:04
Well, That did indeed seems to work

**Comment by zargony** [comment] 2015-05-09 12:06
I don't seem to have this issue with Atom 0.198. Is this still an issue?

**Comment by HitomiTenshi** [comment] 2015-05-17 03:15
This issue still exists, though the real cause is linter-rust. @redefiance's proposed fix does fix the hanging when using linter-rust but that's about it.

To reproduce the issue install:
- linter
- linter-rust

and open up a .rs file, it will make language-rust hang.

This is part of a bigger issue in linter-rust posted here:
https://github.com/AtomLinter/linter-rust/issues/11

**Comment by renkun-ken** [comment] 2015-05-17 03:20
I still have this problem with Atom 0.198.

**Comment by HitomiTenshi** [comment] 2015-05-18 04:31
The issue has been resolved in:
https://github.com/AtomLinter/linter-rust/issues/11

language-rust isn't freezing with linter-rust anymore.

**Comment by zargony** [comment] 2015-05-21 20:24
Great!

**Closed by zargony** 2015-05-21 20:24 UTC
Labels: bug
