### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('i...

### ISSUE THREAD

**Issue by twh2898** [zargony/atom-language-rust#79] opened 2016-07-04 21:05 UTC
### Steps Taken
1. Installed racer and tokamak-terminal packages using native package manager
2. Install tokamak thorugh the package manager
3. The error appears during the installation

**Atom Version**: 1.8.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [language-rust](https://github.com/zargony/atom-language-rust) package, v0.4.6
### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('icon-ion ion-hammer') contains HTML space characters, which are not valid in tokens.

```
At /C:/Users/Thomas/.atom/packages/tool-bar/lib/tool-bar-button-view.js:45

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('icon-ion ion-hammer') contains HTML space characters, which are not valid in tokens.
    at Error (native)
    at new ToolBarButtonView (C:/Users/Thomas/.atom/packages/tool-bar/lib/tool-bar-button-view.js:36:31)
    at ToolBarManager.addButton (C:/Users/Thomas/.atom/packages/tool-bar/lib/tool-bar-manager.js:14:20)
    at Object.module.exports.Tokamak.consumeToolBar (file:///C:/Users/Thomas/.atom/packages/tokamak/lib/tokamak.coffee:124:14)
    at Provider.module.exports.Provider.provide (C:\Users\Thomas\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at C:\Users\Thomas\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```
### Commands

```
     -0:59.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:53.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:46.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:46.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -0:28.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:24.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-python-run",
      "git-control"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-rust, v0.4.6
linter, v1.11.14
linter-rust, v0.4.6
tokamak, v0.2.7
tool-bar, v1.0.0

# Dev
No dev packages
```

**Comment by zargony** [comment] 2017-06-27 12:23
I'm closing this since I can't reproduce it and it doesn't seem to happen to anybody else. The above stack trace shows the exception coming from the tool-bar package (and since language-rust doesn't contain any js code, I don't know how this package should throw an exception anyway)

**Closed by zargony** 2017-06-27 12:23 UTC
